from typing import List, Iterator


class BaseCycle: 
    def __init__(self, cycle: List[int]) -> None: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, key: int) -> int: ...  
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
