from typing import Iterable, Iterator


class BaseCycle: 
    def __init__(self, cycle: Iterable[int]) -> None: ...
    def __iter__(self) -> Iterator[int]: ...
    def __getitem__(self, key: int) -> int: ...  
    def __eq__(self, value) -> bool: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...
