from typing import Dict, Iterator

from .base_cycle import BaseCycle


class BaseSubstitution:
    def __init__(self, substition: Dict) -> None: ...
    def __iter__(self) -> Iterator: ...
    def __getitem__(self, key: int) -> int: ...
    def __setitem__(self, key: int, value: int) -> None: ...
    def __mul__(self, other: 'BaseSubstitution') -> 'BaseSubstitution': ...    
    def __pow__(self, c: int) -> 'BaseSubstitution': ...
    def __repr__(self) -> str: ...
